const { sequelize, Lead, Opportunity, Customer, Contact, Campaign, Maintenance, Organization, Note, Task, CallLog, EmailTemplate } = require('../models');

const DEMO_LEADS = [
  {
    id: 'LEAD-0001',
    firstName: 'Rajesh',
    lastName: 'Sharma',
    email: 'rajesh.sharma@gmail.com',
    mobileNo: '+91 98234 56789',
    jobTitle: 'Business Owner',
    organization: 'Sharma Enterprises',
    status: 'Interested',
    leadSource: 'MagicBricks',
    territory: 'Nashik',
    propertyType: 'Flat',
    budgetRange: '80L - 1Cr',
    preferredArea: 'Gangapur Road',
    followUpDate: '2026-06-25',
    priority: 'High',
    notes: 'Looking for 3BHK. Site visit scheduled.',
    assignedTo: 'Amit Kulkarni',
    createdOn: '12/06/2026',
  },
  {
    id: 'LEAD-0002',
    firstName: 'Priya',
    lastName: 'Mehta',
    email: 'priya.mehta@yahoo.com',
    mobileNo: '+91 97654 32109',
    jobTitle: 'Doctor',
    organization: 'City Hospital',
    status: 'Contacted',
    leadSource: 'Referral',
    territory: 'Nashik Road',
    propertyType: 'Villa',
    budgetRange: '1.5Cr - 2Cr',
    preferredArea: 'Nashik Road',
    followUpDate: '2026-06-22',
    priority: 'Urgent',
    notes: 'Referred by existing customer Mohan Kulkarni.',
    assignedTo: 'Sneha Patil',
    createdOn: '10/06/2026',
  },
  {
    id: 'LEAD-0003',
    firstName: 'Suresh',
    lastName: 'Patil',
    email: 'suresh.patil@gmail.com',
    mobileNo: '+91 96543 21098',
    jobTitle: 'Engineer',
    organization: 'Mahindra',
    status: 'New',
    leadSource: '99acres',
    territory: 'Nashik',
    propertyType: 'Flat',
    budgetRange: '50L - 70L',
    preferredArea: 'College Road',
    followUpDate: '2026-06-28',
    priority: 'Medium',
    notes: 'Interested in 2BHK. Budget is fixed.',
    assignedTo: 'Rahul Desai',
    createdOn: '14/06/2026',
  },
  {
    id: 'LEAD-0004',
    firstName: 'Anita',
    lastName: 'Desai',
    email: 'anita.desai@hotmail.com',
    mobileNo: '+91 95432 10987',
    jobTitle: 'Architect',
    organization: 'Design Studio',
    status: 'Replied',
    leadSource: 'Instagram',
    territory: 'Trimbak Road',
    propertyType: 'Penthouse',
    budgetRange: '3Cr+',
    preferredArea: 'Trimbak Road',
    followUpDate: '2026-06-20',
    priority: 'Urgent',
    notes: 'Wants premium penthouse. Very serious buyer.',
    assignedTo: 'Sneha Patil',
    createdOn: '08/06/2026',
  },
  {
    id: 'LEAD-0005',
    firstName: 'Deepak',
    lastName: 'Joshi',
    email: 'deepak.joshi@gmail.com',
    mobileNo: '+91 94321 09876',
    jobTitle: 'Teacher',
    organization: 'Nashik School',
    status: 'New',
    leadSource: 'Walk-in',
    territory: 'Ozar',
    propertyType: 'Plot',
    budgetRange: '30L - 40L',
    preferredArea: 'Ozar',
    followUpDate: '2026-06-30',
    priority: 'Low',
    notes: 'Walk-in enquiry. Looking for plot.',
    assignedTo: 'Amit Kulkarni',
    createdOn: '15/06/2026',
  },
];

const DEMO_OPPORTUNITIES = [
  {
    id: 'OPP-0001',
    title: '3BHK at Gangapur Road',
    opportunityFrom: 'Lead',
    party: 'Rajesh Sharma',
    status: 'Negotiation',
    amount: 8500000,
    propertyType: 'Flat',
    preferredArea: 'Gangapur Road',
    configuration: '3BHK',
    budgetRange: '80L - 1Cr',
    source: 'MagicBricks',
    expectedCloseDate: '2026-07-15',
    assignedTo: 'Amit Kulkarni',
    priority: 'High',
    linkedLeadId: 'LEAD-0001',
    createdOn: '13/06/2026',
  },
  {
    id: 'OPP-0002',
    title: 'Villa at Nashik Road',
    opportunityFrom: 'Lead',
    party: 'Priya Mehta',
    status: 'Proposal',
    amount: 15000000,
    propertyType: 'Villa',
    preferredArea: 'Nashik Road',
    configuration: 'Villa',
    budgetRange: '1.5Cr - 2Cr',
    source: 'Referral',
    expectedCloseDate: '2026-07-30',
    assignedTo: 'Sneha Patil',
    priority: 'Urgent',
    linkedLeadId: 'LEAD-0002',
    createdOn: '11/06/2026',
  },
  {
    id: 'OPP-0003',
    title: 'Commercial Plot Satpur',
    opportunityFrom: 'Customer',
    party: 'Vikram Industries',
    status: 'Interested',
    amount: 25000000,
    propertyType: 'Commercial',
    preferredArea: 'Satpur MIDC',
    configuration: 'Plot',
    budgetRange: '2.5Cr+',
    source: 'Walk-in',
    expectedCloseDate: '2026-08-01',
    assignedTo: 'Amit Kulkarni',
    priority: 'High',
    linkedLeadId: null,
    createdOn: '09/06/2026',
  },
  {
    id: 'OPP-0004',
    title: 'Penthouse Trimbak Road',
    opportunityFrom: 'Lead',
    party: 'Anita Desai',
    status: 'Open',
    amount: 32000000,
    propertyType: 'Penthouse',
    preferredArea: 'Trimbak Road',
    configuration: 'Penthouse',
    budgetRange: '3Cr+',
    source: 'Instagram',
    expectedCloseDate: '2026-09-01',
    assignedTo: 'Sneha Patil',
    priority: 'Urgent',
    linkedLeadId: 'LEAD-0004',
    createdOn: '09/06/2026',
  },
];

const DEMO_CUSTOMERS = [
  {
    id: 'CUST-0001',
    customerName: 'Mohan Kulkarni',
    customerGroup: 'Individual',
    territory: 'Nashik',
    contactPerson: 'Mohan Kulkarni',
    email: 'mohan.kulkarni@gmail.com',
    mobile: '+91 93212 34567',
    address: 'Flat 302, Suyog Nagar, Nashik',
    gstin: '',
    panNumber: 'ABCPK1234D',
    assignedTo: 'Rahul Desai',
    status: 'Active',
    totalDeals: 1,
    totalValue: 4800000,
    createdOn: '01/03/2026',
  },
  {
    id: 'CUST-0002',
    customerName: 'Vikram Industries',
    customerGroup: 'Company',
    territory: 'Satpur',
    contactPerson: 'Vikram Agarwal',
    email: 'vikram@vikramindustries.com',
    mobile: '+91 92345 67890',
    address: 'Plot 45, Satpur MIDC, Nashik',
    gstin: '27AABCV1234F1Z5',
    panNumber: 'AABCV1234F',
    assignedTo: 'Amit Kulkarni',
    status: 'Active',
    totalDeals: 2,
    totalValue: 35000000,
    createdOn: '15/01/2026',
  },
  {
    id: 'CUST-0003',
    customerName: 'Sunita Bhosale',
    customerGroup: 'Individual',
    territory: 'Nashik Road',
    contactPerson: 'Sunita Bhosale',
    email: 'sunita.bhosale@yahoo.com',
    mobile: '+91 91234 56789',
    address: 'B-12, Panchavati, Nashik',
    gstin: '',
    panNumber: 'BCDPB5678G',
    assignedTo: 'Sneha Patil',
    status: 'Active',
    totalDeals: 1,
    totalValue: 6500000,
    createdOn: '20/02/2026',
  },
];

const DEMO_CONTACTS = [
  {
    id: 'CON-0001',
    firstName: 'Amit',
    lastName: 'Kulkarni',
    email: 'amit.kulkarni@avenubuilders.com',
    mobile: '+91 98765 43210',
    jobTitle: 'Sales Manager',
    company: 'Avenue Builders',
    status: 'Active',
    source: 'Internal',
    createdOn: '01/01/2026',
  },
  {
    id: 'CON-0002',
    firstName: 'Sneha',
    lastName: 'Patil',
    email: 'sneha.patil@avenuebuilders.com',
    mobile: '+91 97654 32109',
    jobTitle: 'Sales Executive',
    company: 'Avenue Builders',
    status: 'Active',
    source: 'Internal',
    createdOn: '01/01/2026',
  },
  {
    id: 'CON-0003',
    firstName: 'Rahul',
    lastName: 'Desai',
    email: 'rahul.desai@avenuebuilders.com',
    mobile: '+91 96543 21098',
    jobTitle: 'Sales Executive',
    company: 'Avenue Builders',
    status: 'Active',
    source: 'Internal',
    createdOn: '01/01/2026',
  },
  {
    id: 'CON-0004',
    firstName: 'Vikram',
    lastName: 'Agarwal',
    email: 'vikram@vikramindustries.com',
    mobile: '+91 92345 67890',
    jobTitle: 'Director',
    company: 'Vikram Industries',
    status: 'Active',
    source: 'Walk-in',
    createdOn: '15/01/2026',
  },
];

const DEMO_CAMPAIGNS = [
  {
    id: 'CMP-0001',
    campaignName: 'Monsoon Offer 2026',
    campaignType: 'Email',
    status: 'Active',
    startDate: '2026-06-01',
    endDate: '2026-07-31',
    budget: 50000,
    leads: 24,
    description: 'Special monsoon discounts on 2BHK flats.',
    createdOn: '01/06/2026',
  },
  {
    id: 'CMP-0002',
    campaignName: 'Instagram Summer Deals',
    campaignType: 'Social Media',
    status: 'Active',
    startDate: '2026-05-15',
    endDate: '2026-06-30',
    budget: 30000,
    leads: 18,
    description: 'Instagram ads for premium villas.',
    createdOn: '15/05/2026',
  },
  {
    id: 'CMP-0003',
    campaignName: 'Referral Bonus Program',
    campaignType: 'Referral',
    status: 'Active',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    budget: 100000,
    leads: 12,
    description: 'Existing customers get ₹25,000 on referral.',
    createdOn: '01/01/2026',
  },
];

const DEMO_MAINTENANCE = [
  {
    id: 'MNT-0001',
    subject: 'Water leakage in bathroom',
    customer: 'Mohan Kulkarni',
    maintenanceType: 'Plumbing',
    status: 'In Progress',
    priority: 'High',
    assignedTo: 'Maintenance Team',
    scheduledDate: '2026-06-20',
    completedDate: '',
    propertyUnit: 'Tower A, Flat 302',
    notes: 'Reported water leakage near bathroom pipe.',
    createdOn: '16/06/2026',
  },
  {
    id: 'MNT-0002',
    subject: 'Main door lock issue',
    customer: 'Sunita Bhosale',
    maintenanceType: 'Carpentry',
    status: 'Scheduled',
    priority: 'Medium',
    assignedTo: 'Maintenance Team',
    scheduledDate: '2026-06-22',
    completedDate: '',
    propertyUnit: 'B-12 Panchavati',
    notes: 'Door lock not working properly.',
    createdOn: '15/06/2026',
  },
  {
    id: 'MNT-0003',
    subject: 'Electrical wiring check',
    customer: 'Vikram Industries',
    maintenanceType: 'Electrical',
    status: 'Open',
    priority: 'Urgent',
    assignedTo: 'Electrical Team',
    scheduledDate: '2026-06-19',
    completedDate: '',
    propertyUnit: 'Plot 45 Satpur MIDC',
    notes: 'Frequent power trips reported.',
    createdOn: '14/06/2026',
  },
];

const DEMO_ORGS = [
  {
    id: 'ORG-0001',
    name: 'Vikram Industries',
    website: 'https://vikramindustries.com',
    industry: 'Manufacturing',
    territory: 'Satpur MIDC',
    noOfEmployees: '201-500',
    annualRevenue: 50000000,
    phone: '+91 92345 67890',
    email: 'info@vikramindustries.com',
    address: 'Plot 45, Satpur MIDC, Nashik',
    description: 'Leading manufacturing firm in Nashik',
    linkedContacts: ['CON-0004'],
    linkedDeals: ['OPP-0003'],
    createdOn: '15/01/2026',
  },
  {
    id: 'ORG-0002',
    name: 'City Hospital',
    website: 'https://cityhospital.in',
    industry: 'Healthcare',
    territory: 'Nashik Road',
    noOfEmployees: '51-200',
    annualRevenue: 20000000,
    phone: '+91 97654 32109',
    email: 'admin@cityhospital.in',
    address: 'Near Railway Station, Nashik Road',
    description: 'Multi-specialty hospital',
    linkedContacts: [],
    linkedDeals: [],
    createdOn: '10/02/2026',
  },
];

const DEMO_NOTES = [
  {
    id: 'NOTE-0001',
    title: 'Site visit feedback - Rajesh',
    content: 'Rajesh visited Gangapur Road site. Very interested in 3BHK corner flat. Needs car parking. Follow up on Monday.',
    linkedTo: 'Rajesh Sharma',
    linkedId: 'LEAD-0001',
    linkedType: 'lead',
    createdBy: 'Amit Kulkarni',
    createdOn: '13/06/2026',
    updatedOn: '13/06/2026',
  },
  {
    id: 'NOTE-0002',
    title: 'Negotiation notes - Anita Desai',
    content: 'Client wants 5% discount on penthouse. Offered 2% + free parking. She will discuss with family. Expected decision by end of week.',
    linkedTo: 'Anita Desai',
    linkedId: 'LEAD-0004',
    linkedType: 'lead',
    createdBy: 'Sneha Patil',
    createdOn: '15/06/2026',
    updatedOn: '16/06/2026',
  },
  {
    id: 'NOTE-0003',
    title: 'Commercial deal requirements',
    content: 'Vikram Industries needs warehouse space. Minimum 5000 sq ft. Road access mandatory. Budget flexible if location is right.',
    linkedTo: 'Vikram Industries',
    linkedId: 'OPP-0003',
    linkedType: 'deal',
    createdBy: 'Amit Kulkarni',
    createdOn: '10/06/2026',
    updatedOn: '10/06/2026',
  },
];

const DEMO_TASKS = [
  {
    id: 'TASK-0001',
    title: 'Follow up call with Rajesh Sharma',
    description: 'Call regarding 3BHK availability and pricing at Gangapur Road.',
    status: 'Open',
    assignedTo: 'Amit Kulkarni',
    dueDate: '2026-06-22',
    priority: 'High',
    linkedTo: 'Rajesh Sharma',
    linkedId: 'LEAD-0001',
    linkedType: 'lead',
    done: false,
    createdOn: '16/06/2026',
  },
  {
    id: 'TASK-0002',
    title: 'Send proposal to Vikram Industries',
    description: 'Prepare and send commercial plot proposal with pricing.',
    status: 'Open',
    assignedTo: 'Amit Kulkarni',
    dueDate: '2026-06-20',
    priority: 'Urgent',
    linkedTo: 'Vikram Industries',
    linkedId: 'OPP-0003',
    linkedType: 'deal',
    done: false,
    createdOn: '14/06/2026',
  },
  {
    id: 'TASK-0003',
    title: 'Site visit arrangement for Priya',
    description: 'Arrange villa site visit at Nashik Road property.',
    status: 'Replied',
    assignedTo: 'Sneha Patil',
    dueDate: '2026-06-21',
    priority: 'Medium',
    linkedTo: 'Priya Mehta',
    linkedId: 'LEAD-0002',
    linkedType: 'lead',
    done: false,
    createdOn: '12/06/2026',
  },
  {
    id: 'TASK-0004',
    title: 'Send agreement to Mohan Kulkarni',
    description: 'Send signed agreement copy for flat 302.',
    status: 'Closed',
    assignedTo: 'Rahul Desai',
    dueDate: '2026-06-10',
    priority: 'Low',
    linkedTo: 'Mohan Kulkarni',
    linkedId: 'CUST-0001',
    linkedType: 'customer',
    done: true,
    createdOn: '08/06/2026',
  },
];

const DEMO_CALLLOGS = [
  {
    id: 'CALL-0001',
    to: 'Rajesh Sharma',
    from: 'Amit Kulkarni',
    duration: '8 mins',
    status: 'Completed',
    outcome: 'Completed',
    notes: 'Discussed 3BHK pricing. Customer interested, wants site visit.',
    recordingUrl: '',
    linkedTo: 'Rajesh Sharma',
    linkedId: 'LEAD-0001',
    linkedType: 'lead',
    callType: 'outbound',
    createdBy: 'Amit Kulkarni',
    createdOn: '13/06/2026',
  },
  {
    id: 'CALL-0002',
    to: 'Priya Mehta',
    from: 'Sneha Patil',
    duration: '12 mins',
    status: 'Completed',
    outcome: 'Completed',
    notes: 'Villa details discussed. Priya wants 3D walkthrough.',
    recordingUrl: '',
    linkedTo: 'Priya Mehta',
    linkedId: 'LEAD-0002',
    linkedType: 'lead',
    callType: 'outbound',
    createdBy: 'Sneha Patil',
    createdOn: '11/06/2026',
  },
  {
    id: 'CALL-0003',
    to: 'Amit Kulkarni',
    from: 'Anita Desai',
    duration: '5 mins',
    status: 'Completed',
    outcome: 'Completed',
    notes: 'Inbound — Anita called to ask about penthouse availability.',
    recordingUrl: '',
    linkedTo: 'Anita Desai',
    linkedId: 'LEAD-0004',
    linkedType: 'lead',
    callType: 'inbound',
    createdBy: 'Amit Kulkarni',
    createdOn: '15/06/2026',
  },
  {
    id: 'CALL-0004',
    to: 'Suresh Patil',
    from: 'Rahul Desai',
    duration: '0 mins',
    status: 'No Answer',
    outcome: 'No Answer',
    notes: 'Called twice, no answer.',
    recordingUrl: '',
    linkedTo: 'Suresh Patil',
    linkedId: 'LEAD-0003',
    linkedType: 'lead',
    callType: 'outbound',
    createdBy: 'Rahul Desai',
    createdOn: '14/06/2026',
  },
];

const DEMO_TEMPLATES = [
  {
    id: 'TMPL-0001',
    name: 'Welcome Email',
    subject: 'Welcome to Avenue Builders — {{lead_name}}',
    body: '<p>Dear {{lead_name}},</p><p>Thank you for your interest in Avenue Builders. We are delighted to assist you in finding your dream property.</p><p>Our team will contact you shortly to discuss your requirements.</p><p>Warm regards,<br/>{{owner_name}}<br/>Avenue Builders</p>',
    category: 'Lead',
    createdBy: 'Admin User',
    createdOn: '01/01/2026',
  },
  {
    id: 'TMPL-0002',
    name: 'Site Visit Confirmation',
    subject: 'Site Visit Confirmed — {{property_name}}',
    body: '<p>Dear {{lead_name}},</p><p>Your site visit has been confirmed for {{visit_date}} at {{property_address}}.</p><p>Please bring a valid ID proof. Our representative {{owner_name}} will meet you at the site.</p><p>Looking forward to seeing you!</p><p>Avenue Builders Team</p>',
    category: 'Lead',
    createdBy: 'Admin User',
    createdOn: '01/01/2026',
  },
  {
    id: 'TMPL-0003',
    name: 'Deal Won — Thank You',
    subject: 'Congratulations on Your New Property!',
    body: '<p>Dear {{customer_name}},</p><p>Congratulations! We are thrilled to welcome you to the Avenue Builders family.</p><p>Your property {{property_name}} has been successfully registered.</p><p>Our team is here for any support you need going forward.</p><p>Thank you for choosing us!</p><p>Warm regards,<br/>Avenue Builders</p>',
    category: 'Deal',
    createdBy: 'Admin User',
    createdOn: '01/01/2026',
  },
  {
    id: 'TMPL-0004',
    name: 'Follow-up Reminder',
    subject: 'Following up — {{property_name}}',
    body: '<p>Dear {{lead_name}},</p><p>I hope you are doing well. I wanted to follow up regarding your interest in {{property_name}}.</p><p>We have some exciting updates and special offers available. Would you be available for a quick call this week?</p><p>Best regards,<br/>{{owner_name}}<br/>Avenue Builders</p>',
    category: 'Lead',
    createdBy: 'Amit Kulkarni',
    createdOn: '05/01/2026',
  },
];

const seedDatabase = async () => {
  try {
    console.log('Syncing database tables...');
    await sequelize.sync({ force: true });
    console.log('Database synced successfully.');

    console.log('Seeding Leads...');
    await Lead.bulkCreate(DEMO_LEADS);

    console.log('Seeding Customers...');
    await Customer.bulkCreate(DEMO_CUSTOMERS);

    console.log('Seeding Opportunities...');
    await Opportunity.bulkCreate(DEMO_OPPORTUNITIES);

    console.log('Seeding Contacts...');
    await Contact.bulkCreate(DEMO_CONTACTS);

    console.log('Seeding Campaigns...');
    await Campaign.bulkCreate(DEMO_CAMPAIGNS);

    console.log('Seeding Maintenances...');
    await Maintenance.bulkCreate(DEMO_MAINTENANCE);

    console.log('Seeding Organizations...');
    await Organization.bulkCreate(DEMO_ORGS);

    console.log('Seeding Notes...');
    await Note.bulkCreate(DEMO_NOTES);

    console.log('Seeding Tasks...');
    await Task.bulkCreate(DEMO_TASKS);

    console.log('Seeding Call Logs...');
    await CallLog.bulkCreate(DEMO_CALLLOGS);

    console.log('Seeding Email Templates...');
    await EmailTemplate.bulkCreate(DEMO_TEMPLATES);

    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
