const { sequelize, Lead } = require('./models');

const leads30 = [
  {
    salutation: 'Mr',
    firstName: 'Aarav',
    lastName: 'Sharma',
    email: 'aarav.sharma@techverse.in',
    mobileNo: '9823011223',
    gender: 'Male',
    organization: 'TechVerse Innovations',
    website: 'www.techverse.in',
    noOfEmployees: '50-100',
    territory: 'Mumbai',
    annualRevenue: 12000000.00,
    industry: 'Technology',
    status: 'New',
    leadOwner: 'Admin User',
    leadSource: 'Google Ads',
    jobTitle: 'VP of Technology',
    propertyType: '3 BHK Apartment',
    budgetRange: '1.2 Cr - 1.8 Cr',
    preferredArea: 'Bandra West',
    followUpDate: '2026-08-10',
    priority: 'High',
    notes: 'Looking for modern office space / residential unit near IT park.'
  },
  {
    salutation: 'Ms',
    firstName: 'Priya',
    lastName: 'Verma',
    email: 'priya.verma@apexhealth.com',
    mobileNo: '9876543210',
    gender: 'Female',
    organization: 'Apex Health Systems',
    website: 'www.apexhealth.com',
    noOfEmployees: '100-500',
    territory: 'Delhi NCR',
    annualRevenue: 45000000.00,
    industry: 'Healthcare',
    status: 'In Discussion',
    leadOwner: 'Admin User',
    leadSource: 'LinkedIn',
    jobTitle: 'Chief Medical Officer',
    propertyType: 'Commercial Space',
    budgetRange: '3.5 Cr - 5 Cr',
    preferredArea: 'Cyber City',
    followUpDate: '2026-08-12',
    priority: 'High',
    notes: 'Requires 3,000 sq ft space for specialized outpatient center.'
  },
  {
    salutation: 'Mr',
    firstName: 'Rohan',
    lastName: 'Mehta',
    email: 'rohan@mehtacapital.com',
    mobileNo: '9920198765',
    gender: 'Male',
    organization: 'Mehta Capital Group',
    website: 'www.mehtacapital.com',
    noOfEmployees: '20-50',
    territory: 'Mumbai',
    annualRevenue: 85000000.00,
    industry: 'Finance',
    status: 'Qualified',
    leadOwner: 'Admin User',
    leadSource: 'Referral',
    jobTitle: 'Managing Partner',
    propertyType: 'Penthouse',
    budgetRange: '4 Cr - 6 Cr',
    preferredArea: 'Worli',
    followUpDate: '2026-08-11',
    priority: 'High',
    notes: 'High net worth client looking for luxury sea-facing penthouse.'
  },
  {
    salutation: 'Mrs',
    firstName: 'Ananya',
    lastName: 'Iyer',
    email: 'ananya.iyer@greensolutions.org',
    mobileNo: '9444123890',
    gender: 'Female',
    organization: 'Green Solutions Eco',
    website: 'www.greensolutions.org',
    noOfEmployees: '10-20',
    territory: 'Bengaluru',
    annualRevenue: 8000000.00,
    industry: 'Renewable Energy',
    status: 'Proposal Sent',
    leadOwner: 'Admin User',
    leadSource: 'Website Inquiry',
    jobTitle: 'Operations Director',
    propertyType: 'Independent Villa',
    budgetRange: '2 Cr - 3 Cr',
    preferredArea: 'Koramangala',
    followUpDate: '2026-08-15',
    priority: 'Medium',
    notes: 'Proposal sent for solar-enabled eco villas.'
  },
  {
    salutation: 'Mr',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram@singhlogistics.com',
    mobileNo: '9711223344',
    gender: 'Male',
    organization: 'Singh Global Logistics',
    website: 'www.singhlogistics.com',
    noOfEmployees: '200-500',
    territory: 'Pune',
    annualRevenue: 120000000.00,
    industry: 'Logistics',
    status: 'Negotiation',
    leadOwner: 'Admin User',
    leadSource: 'Trade Expo',
    jobTitle: 'Head of Supply Chain',
    propertyType: 'Industrial Warehouse',
    budgetRange: '5 Cr - 8 Cr',
    preferredArea: 'Chakan Industrial Zone',
    followUpDate: '2026-08-09',
    priority: 'High',
    notes: 'Wants 20,000 sq ft covered warehouse facility with dock levellers.'
  },
  {
    salutation: 'Dr',
    firstName: 'Siddharth',
    lastName: 'Joshi',
    email: 'dr.joshi@nashikdental.com',
    mobileNo: '9822998877',
    gender: 'Male',
    organization: 'Joshi Dental Care',
    website: 'www.nashikdental.com',
    noOfEmployees: '5-10',
    territory: 'Nashik',
    annualRevenue: 3500000.00,
    industry: 'Healthcare',
    status: 'Site Visit Scheduled',
    leadOwner: 'Admin User',
    leadSource: 'Meta Ads',
    jobTitle: 'Owner / Chief Dentist',
    propertyType: 'Commercial Shop',
    budgetRange: '80 L - 1.2 Cr',
    preferredArea: 'College Road',
    followUpDate: '2026-08-13',
    priority: 'Medium',
    notes: 'Wants ground floor retail unit with dedicated patient parking.'
  },
  {
    salutation: 'Ms',
    firstName: 'Kavita',
    lastName: 'Deshmukh',
    email: 'kavita.d@bluedarttech.com',
    mobileNo: '9890123456',
    gender: 'Female',
    organization: 'BlueDart Softwares',
    website: '',
    noOfEmployees: '10-50',
    territory: 'Pune',
    annualRevenue: 9500000.00,
    industry: 'Software',
    status: 'Contacted',
    leadOwner: 'Admin User',
    leadSource: 'Cold Outreach',
    jobTitle: 'HR Head',
    propertyType: '2 BHK Apartment',
    budgetRange: '65 L - 85 L',
    preferredArea: 'Hinjewadi',
    followUpDate: '2026-08-14',
    priority: 'Low',
    notes: 'Looking for corporate housing options for relocated employees.'
  },
  {
    salutation: 'Mr',
    firstName: 'Karan',
    lastName: 'Kapoor',
    email: 'karan.kapoor@kapoorfabrics.com',
    mobileNo: '9810011223',
    gender: 'Male',
    organization: 'Kapoor Textile Fabrics',
    website: 'www.kapoorfabrics.com',
    noOfEmployees: '100-250',
    territory: 'Ahmedabad',
    annualRevenue: 60000000.00,
    industry: 'Textiles',
    status: 'New',
    leadOwner: 'Admin User',
    leadSource: 'Google Ads',
    jobTitle: 'Executive Director',
    propertyType: 'Commercial Showroom',
    budgetRange: '2.5 Cr - 4 Cr',
    preferredArea: 'SG Highway',
    followUpDate: '2026-08-16',
    priority: 'High',
    notes: 'Interested in flagship retail showroom on main highway.'
  },
  {
    salutation: 'Mrs',
    firstName: 'Pooja',
    lastName: 'Nair',
    email: 'pooja.nair@nairconsulting.in',
    mobileNo: '9744556677',
    gender: 'Female',
    organization: 'Nair Financial Advisors',
    website: 'www.nairconsulting.in',
    noOfEmployees: '1-10',
    territory: 'Kochi',
    annualRevenue: 4000000.00,
    industry: 'Consulting',
    status: 'Qualified',
    leadOwner: 'Admin User',
    leadSource: 'Referral',
    jobTitle: 'Principal Consultant',
    propertyType: '3 BHK Apartment',
    budgetRange: '90 L - 1.3 Cr',
    preferredArea: 'Marine Drive',
    followUpDate: '2026-08-11',
    priority: 'Medium',
    notes: 'Wants waterfront apartment with smart home automation.'
  },
  {
    salutation: 'Mr',
    firstName: 'Manish',
    lastName: 'Gupta',
    email: 'manish@guptabuilders.com',
    mobileNo: '9833445566',
    gender: 'Male',
    organization: 'Gupta Construction Co',
    website: 'www.guptabuilders.com',
    noOfEmployees: '50-100',
    territory: 'Mumbai',
    annualRevenue: 30000000.00,
    industry: 'Real Estate',
    status: 'Won',
    leadOwner: 'Admin User',
    leadSource: 'Partner Program',
    jobTitle: 'Founder',
    propertyType: 'Joint Development Land',
    budgetRange: '10 Cr - 15 Cr',
    preferredArea: 'Thane West',
    followUpDate: '2026-08-08',
    priority: 'High',
    notes: 'Closed joint venture deal for 2-acre residential township development.'
  },
  {
    salutation: 'Mr',
    firstName: 'Rajesh',
    lastName: 'Kulkarni',
    email: 'rajesh.k@kulkarniauto.com',
    mobileNo: '9822334455',
    gender: 'Male',
    organization: 'Kulkarni Auto Ancillaries',
    website: 'www.kulkarniauto.com',
    noOfEmployees: '100-200',
    territory: 'Nashik',
    annualRevenue: 40000000.00,
    industry: 'Automotive',
    status: 'In Discussion',
    leadOwner: 'Admin User',
    leadSource: 'Industrial Expo',
    jobTitle: 'Managing Director',
    propertyType: 'Industrial Plot',
    budgetRange: '3 Cr - 4.5 Cr',
    preferredArea: 'Ambad MIDC',
    followUpDate: '2026-08-12',
    priority: 'High',
    notes: 'Expanding manufacturing unit, requires 1 acre MIDC plot.'
  },
  {
    salutation: 'Ms',
    firstName: 'Shweta',
    lastName: 'Patel',
    email: 'shweta@designstudio.co.in',
    mobileNo: '9898012345',
    gender: 'Female',
    organization: 'Urban Space Design Studio',
    website: 'www.designstudio.co.in',
    noOfEmployees: '10-20',
    territory: 'Surat',
    annualRevenue: 6500000.00,
    industry: 'Architecture & Design',
    status: 'New',
    leadOwner: 'Admin User',
    leadSource: 'Instagram Ads',
    jobTitle: 'Lead Interior Architect',
    propertyType: 'Office Suite',
    budgetRange: '50 L - 75 L',
    preferredArea: 'Vesu',
    followUpDate: '2026-08-17',
    priority: 'Medium',
    notes: 'Seeking creative office space with open glass facade.'
  },
  {
    salutation: 'Mr',
    firstName: 'Deepak',
    lastName: 'Chawla',
    email: 'deepak.c@chawlagroup.in',
    mobileNo: '9811224466',
    gender: 'Male',
    organization: 'Chawla Hospitality Group',
    website: 'www.chawlagroup.in',
    noOfEmployees: '200-500',
    territory: 'Jaipur',
    annualRevenue: 75000000.00,
    industry: 'Hospitality',
    status: 'Proposal Sent',
    leadOwner: 'Admin User',
    leadSource: 'Direct Sales',
    jobTitle: 'Director of Expansion',
    propertyType: 'Boutique Hotel Property',
    budgetRange: '12 Cr - 18 Cr',
    preferredArea: 'C-Scheme',
    followUpDate: '2026-08-18',
    priority: 'High',
    notes: 'Proposal sent for heritage conversion property in city center.'
  },
  {
    salutation: 'Mrs',
    firstName: 'Meera',
    lastName: 'Rao',
    email: 'meera.rao@raofoods.com',
    mobileNo: '9845019283',
    gender: 'Female',
    organization: 'Rao Gourmet Foods',
    website: 'www.raofoods.com',
    noOfEmployees: '50-100',
    territory: 'Bengaluru',
    annualRevenue: 18000000.00,
    industry: 'Food & Beverage',
    status: 'Site Visit Scheduled',
    leadOwner: 'Admin User',
    leadSource: 'Google Search',
    jobTitle: 'Founder & CEO',
    propertyType: 'Central Kitchen Space',
    budgetRange: '1 Cr - 1.6 Cr',
    preferredArea: 'Whitefield',
    followUpDate: '2026-08-13',
    priority: 'Medium',
    notes: 'Requires 4,000 sq ft cloud kitchen ready space.'
  },
  {
    salutation: 'Mr',
    firstName: 'Abhishek',
    lastName: 'Tiwari',
    email: 'abhishek.t@tiwaripharmaceuticals.com',
    mobileNo: '9935112233',
    gender: 'Male',
    organization: 'Tiwari Pharmaceuticals',
    website: 'www.tiwaripharmaceuticals.com',
    noOfEmployees: '100-300',
    territory: 'Lucknow',
    annualRevenue: 55000000.00,
    industry: 'Pharmaceuticals',
    status: 'Negotiation',
    leadOwner: 'Admin User',
    leadSource: 'Referral',
    jobTitle: 'VP Operations',
    propertyType: 'Cold Storage Warehouse',
    budgetRange: '4 Cr - 6 Cr',
    preferredArea: 'Transport Nagar',
    followUpDate: '2026-08-10',
    priority: 'High',
    notes: 'Finalizing lease terms for temperature-controlled pharma hub.'
  },
  {
    salutation: 'Ms',
    firstName: 'Neha',
    lastName: 'Bhasin',
    email: 'neha.bhasin@eduskills.org',
    mobileNo: '9818901234',
    gender: 'Female',
    organization: 'EduSkills Foundation',
    website: 'www.eduskills.org',
    noOfEmployees: '20-50',
    territory: 'Delhi NCR',
    annualRevenue: 7000000.00,
    industry: 'Education',
    status: 'Contacted',
    leadOwner: 'Admin User',
    leadSource: 'Webinar',
    jobTitle: 'Program Director',
    propertyType: 'Training Center Facility',
    budgetRange: '70 L - 1 Cr',
    preferredArea: 'Noida Sector 62',
    followUpDate: '2026-08-19',
    priority: 'Low',
    notes: 'Looking for 1,500 sq ft setup for student skill training.'
  },
  {
    salutation: 'Mr',
    firstName: 'Gaurav',
    lastName: 'Pandey',
    email: 'gaurav@pandeylogistics.co.in',
    mobileNo: '9827011223',
    gender: 'Male',
    organization: 'Pandey Freight Carriers',
    website: '',
    noOfEmployees: '50-100',
    territory: 'Indore',
    annualRevenue: 22000000.00,
    industry: 'Logistics',
    status: 'New',
    leadOwner: 'Admin User',
    leadSource: 'Justdial',
    jobTitle: 'General Manager',
    propertyType: 'Commercial Land',
    budgetRange: '1.5 Cr - 2.2 Cr',
    preferredArea: 'Bypass Road',
    followUpDate: '2026-08-20',
    priority: 'Medium',
    notes: 'Wants truck yard space near highway exit.'
  },
  {
    salutation: 'Mrs',
    firstName: 'Ritu',
    lastName: 'Saxena',
    email: 'ritu.saxena@saxenalaw.in',
    mobileNo: '9811122334',
    gender: 'Female',
    organization: 'Saxena & Partners Law Firm',
    website: 'www.saxenalaw.in',
    noOfEmployees: '10-30',
    territory: 'Delhi NCR',
    annualRevenue: 14000000.00,
    industry: 'Legal Services',
    status: 'Qualified',
    leadOwner: 'Admin User',
    leadSource: 'Referral',
    jobTitle: 'Senior Partner',
    propertyType: 'Office Space',
    budgetRange: '1.8 Cr - 2.5 Cr',
    preferredArea: 'Connaught Place',
    followUpDate: '2026-08-12',
    priority: 'High',
    notes: 'Client wants prestigious address near High Court.'
  },
  {
    salutation: 'Mr',
    firstName: 'Nikhil',
    lastName: 'Kamath',
    email: 'nikhil@kamathenterprises.com',
    mobileNo: '9845112244',
    gender: 'Male',
    organization: 'Kamath Trading Enterprises',
    website: 'www.kamathenterprises.com',
    noOfEmployees: '30-80',
    territory: 'Mangalore',
    annualRevenue: 28000000.00,
    industry: 'Wholesale & Retail',
    status: 'In Discussion',
    leadOwner: 'Admin User',
    leadSource: 'Meta Ads',
    jobTitle: 'Proprietor',
    propertyType: 'Retail Storefront',
    budgetRange: '1.2 Cr - 1.8 Cr',
    preferredArea: 'MG Road',
    followUpDate: '2026-08-14',
    priority: 'Medium',
    notes: 'Wants corner property on commercial high street.'
  },
  {
    salutation: 'Dr',
    firstName: 'Anita',
    lastName: 'Roy',
    email: 'dr.anita@royeyeclinic.org',
    mobileNo: '9830012345',
    gender: 'Female',
    organization: 'Roy Super Specialty Eye Care',
    website: 'www.royeyeclinic.org',
    noOfEmployees: '15-40',
    territory: 'Kolkata',
    annualRevenue: 16000000.00,
    industry: 'Healthcare',
    status: 'Proposal Sent',
    leadOwner: 'Admin User',
    leadSource: 'Doctor Referral',
    jobTitle: 'Medical Director',
    propertyType: 'Standalone Building',
    budgetRange: '3 Cr - 4.5 Cr',
    preferredArea: 'Salt Lake Sector 5',
    followUpDate: '2026-08-15',
    priority: 'High',
    notes: 'Sent floor plans for 3-story healthcare facility.'
  },
  {
    salutation: 'Mr',
    firstName: 'Harish',
    lastName: 'Shetty',
    email: 'harish.shetty@shettyconstructions.com',
    mobileNo: '9820098765',
    gender: 'Male',
    organization: 'Shetty Infra Projects',
    website: 'www.shettyconstructions.com',
    noOfEmployees: '100-300',
    territory: 'Mumbai',
    annualRevenue: 90000000.00,
    industry: 'Infrastructure',
    status: 'New',
    leadOwner: 'Admin User',
    leadSource: 'Newspaper Ad',
    jobTitle: 'Chairman',
    propertyType: 'Commercial Land',
    budgetRange: '15 Cr - 25 Cr',
    preferredArea: 'Navi Mumbai',
    followUpDate: '2026-08-21',
    priority: 'High',
    notes: 'Looking for prime commercial land near upcoming airport.'
  },
  {
    salutation: 'Ms',
    firstName: 'Divya',
    lastName: 'Bansal',
    email: 'divya@bansaljewellers.com',
    mobileNo: '9810123456',
    gender: 'Female',
    organization: 'Bansal Heritage Jewellers',
    website: 'www.bansaljewellers.com',
    noOfEmployees: '20-50',
    territory: 'Chandigarh',
    annualRevenue: 48000000.00,
    industry: 'Jewelry & Luxury',
    status: 'Site Visit Scheduled',
    leadOwner: 'Admin User',
    leadSource: 'Event Sponsor',
    jobTitle: 'Managing Partner',
    propertyType: 'Showroom Space',
    budgetRange: '4 Cr - 6 Cr',
    preferredArea: 'Sector 17',
    followUpDate: '2026-08-11',
    priority: 'High',
    notes: 'High-security showroom space requirement with strong vault room provisions.'
  },
  {
    salutation: 'Mr',
    firstName: 'Tarun',
    lastName: 'Malhotra',
    email: 'tarun@malhotramotors.in',
    mobileNo: '9871122334',
    gender: 'Male',
    organization: 'Malhotra EV Motors',
    website: 'www.malhotramotors.in',
    noOfEmployees: '50-150',
    territory: 'Gurugram',
    annualRevenue: 35000000.00,
    industry: 'Automotive / EV',
    status: 'Negotiation',
    leadOwner: 'Admin User',
    leadSource: 'Google Ads',
    jobTitle: 'Head of Dealerships',
    propertyType: 'EV Dealership Experience Center',
    budgetRange: '3 Cr - 5 Cr',
    preferredArea: 'Golf Course Road',
    followUpDate: '2026-08-10',
    priority: 'High',
    notes: 'Negotiating rent terms for 5,000 sq ft glass showroom.'
  },
  {
    salutation: 'Mrs',
    firstName: 'Sunita',
    lastName: 'Menon',
    email: 'sunita.menon@menonsolutions.com',
    mobileNo: '9847012345',
    gender: 'Female',
    organization: 'Menon HR Solutions',
    website: 'www.menonsolutions.com',
    noOfEmployees: '10-25',
    territory: 'Trivandrum',
    annualRevenue: 5000000.00,
    industry: 'Human Resources',
    status: 'Contacted',
    leadOwner: 'Admin User',
    leadSource: 'LinkedIn',
    jobTitle: 'Chief HR Officer',
    propertyType: 'Co-working Office Desks',
    budgetRange: '30 L - 50 L',
    preferredArea: 'Technopark Phase 3',
    followUpDate: '2026-08-22',
    priority: 'Low',
    notes: 'Needs 25 dedicated workstations with high speed fiber internet.'
  },
  {
    salutation: 'Mr',
    firstName: 'Alok',
    lastName: 'Srivastava',
    email: 'alok@srivastavaengineering.com',
    mobileNo: '9415012345',
    gender: 'Male',
    organization: 'Srivastava Heavy Engineering',
    website: 'www.srivastavaengineering.com',
    noOfEmployees: '150-400',
    territory: 'Kanpur',
    annualRevenue: 65000000.00,
    industry: 'Manufacturing',
    status: 'New',
    leadOwner: 'Admin User',
    leadSource: 'Exhibition',
    jobTitle: 'Technical Director',
    propertyType: 'Factory Shed',
    budgetRange: '4 Cr - 7 Cr',
    preferredArea: 'Panki Industrial Area',
    followUpDate: '2026-08-23',
    priority: 'Medium',
    notes: 'Requires heavy-duty industrial shed with 15-ton overhead crane capacity.'
  },
  {
    salutation: 'Ms',
    firstName: 'Pooja',
    lastName: 'Thakur',
    email: 'pooja@thakurorganics.com',
    mobileNo: '9816012345',
    gender: 'Female',
    organization: 'Thakur Organic Farms',
    website: 'www.thakurorganics.com',
    noOfEmployees: '20-60',
    territory: 'Shimla',
    annualRevenue: 8000000.00,
    industry: 'Agriculture / Organics',
    status: 'Qualified',
    leadOwner: 'Admin User',
    leadSource: 'Organic Search',
    jobTitle: 'Managing Partner',
    propertyType: 'Agricultural Land / Orchard',
    budgetRange: '1 Cr - 1.8 Cr',
    preferredArea: 'Kufri Road',
    followUpDate: '2026-08-13',
    priority: 'Medium',
    notes: 'Looking for 5-acre apple orchard property for eco-tourism stay.'
  },
  {
    salutation: 'Mr',
    firstName: 'Yash',
    lastName: 'Aggarwal',
    email: 'yash@aggarwalcoldchain.com',
    mobileNo: '9810987654',
    gender: 'Male',
    organization: 'Aggarwal Cold Chain Logistics',
    website: 'www.aggarwalcoldchain.com',
    noOfEmployees: '80-200',
    territory: 'Panipat',
    annualRevenue: 32000000.00,
    industry: 'Logistics',
    status: 'In Discussion',
    leadOwner: 'Admin User',
    leadSource: 'Referral',
    jobTitle: 'Operations Manager',
    propertyType: 'Logistics Park Parcel',
    budgetRange: '2.5 Cr - 4 Cr',
    preferredArea: 'GT Road Corridor',
    followUpDate: '2026-08-14',
    priority: 'High',
    notes: 'Requires strategically located land parcel along GT Road.'
  },
  {
    salutation: 'Mrs',
    firstName: 'Shalini',
    lastName: 'Dube',
    email: 'shalini.dube@dubefashions.com',
    mobileNo: '9826012345',
    gender: 'Female',
    organization: 'Dube Couture & Fashions',
    website: 'www.dubefashions.com',
    noOfEmployees: '15-35',
    territory: 'Bhopal',
    annualRevenue: 9000000.00,
    industry: 'Apparel & Fashion',
    status: 'Won',
    leadOwner: 'Admin User',
    leadSource: 'Instagram',
    jobTitle: 'Creative Founder',
    propertyType: 'Designer Boutique Studio',
    budgetRange: '60 L - 90 L',
    preferredArea: 'Arera Colony',
    followUpDate: '2026-08-08',
    priority: 'Medium',
    notes: 'Agreement signed for high-end boutique location in Arera Colony.'
  },
  {
    salutation: 'Mr',
    firstName: 'Vikas',
    lastName: 'Rathore',
    email: 'vikas.r@rathoreminerals.in',
    mobileNo: '9414012345',
    gender: 'Male',
    organization: 'Rathore Minerals & Mining',
    website: 'www.rathoreminerals.in',
    noOfEmployees: '150-500',
    territory: 'Udaipur',
    annualRevenue: 110000000.00,
    industry: 'Mining & Materials',
    status: 'New',
    leadOwner: 'Admin User',
    leadSource: 'Trade Directory',
    jobTitle: 'Director',
    propertyType: 'Corporate Office HQ',
    budgetRange: '3.5 Cr - 5.5 Cr',
    preferredArea: 'Fatehpura',
    followUpDate: '2026-08-25',
    priority: 'High',
    notes: 'Company expanding corporate HQ, searching for 8,000 sq ft office building.'
  },
  {
    salutation: 'Ms',
    firstName: 'Richa',
    lastName: 'Choudhary',
    email: 'richa@fintechpulse.io',
    mobileNo: '9880012345',
    gender: 'Female',
    organization: 'FinTech Pulse Payments',
    website: 'www.fintechpulse.io',
    noOfEmployees: '40-100',
    territory: 'Bengaluru',
    annualRevenue: 25000000.00,
    industry: 'Fintech',
    status: 'Proposal Sent',
    leadOwner: 'Admin User',
    leadSource: 'AngelList',
    jobTitle: 'Head of Growth',
    propertyType: 'Tech Park Floor',
    budgetRange: '2 Cr - 3.2 Cr',
    preferredArea: 'Outer Ring Road (ORR)',
    followUpDate: '2026-08-16',
    priority: 'High',
    notes: 'Proposal sent for plug-and-play 60-seater office in grade-A tech park.'
  }
];

const seed30Leads = async () => {
  try {
    console.log('Connecting to database...');
    await sequelize.authenticate();
    await sequelize.sync();

    console.log('Inserting 30 Leads...');
    let count = 0;
    for (let i = 0; i < leads30.length; i++) {
      const numStr = String(i + 1).padStart(4, '0');
      const leadId = `LEAD-${numStr}`;
      
      const leadData = {
        id: leadId,
        createdOn: new Date().toISOString().split('T')[0],
        ...leads30[i]
      };

      const existing = await Lead.findByPk(leadId);
      if (existing) {
        await existing.update(leadData);
      } else {
        await Lead.create(leadData);
      }
      count++;
    }

    console.log(`Successfully seeded ${count} leads into the database!`);
    process.exit(0);
  } catch (err) {
    console.error('Error seeding 30 leads:', err);
    process.exit(1);
  }
};

seed30Leads();
